### PR TITLE
declare java_stdout as string

### LINKED ISSUE #11: Java fact typerror with Python 3
**Running Java fact with Python 3 returns a typerror.**

_file: templates/etc/ansible/facts.d/java.fact.j2_

```
# python3 --version
Python 3.8.5
# python3 java.fact.j2 
Traceback (most recent call last):
  File "java.fact.j2", line 24, in <module>
    for line in java_stdout.split('\n'):
TypeError: a bytes-like object is required, not 'str'
```

### PR DESCRIPTION
**Pull request by juanmancebo**
closes #11

### CODE REVIEW

File: templates/etc/ansible/facts.d/java.fact.j2 [hunk 1]
```diff
@@ -21,6 +21,7 @@ except subprocess.CalledProcessError:
     pass
 
 if java_stdout:
+	java_stdout = str(java_stdout)
```
Comment (ki0) [inline templates/etc/ansible/facts.d/java.fact.j2:24]: I think indentation is not correct, in python it is important.
